// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./Utils.bs.js");
var TextArea$ReactTemplate = require("./TextArea.bs.js");
var TextField$ReactTemplate = require("./TextField.bs.js");
var MultipleChoices$ReactTemplate = require("./MultipleChoices.bs.js");
var AlternateChoices$ReactTemplate = require("./AlternateChoices.bs.js");

var component = ReasonReact.statelessComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, Utils$ReactTemplate.s("ReasonML Survey")), Utils$ReactTemplate.mapi((function (index, question) {
                                var tmp;
                                switch (question.tag | 0) {
                                  case 0 : 
                                      tmp = ReasonReact.element(undefined, undefined, TextField$ReactTemplate.make(question[0], /* array */[]));
                                      break;
                                  case 1 : 
                                      tmp = ReasonReact.element(undefined, undefined, TextArea$ReactTemplate.make(question[0], /* array */[]));
                                      break;
                                  case 2 : 
                                      tmp = ReasonReact.element(undefined, undefined, AlternateChoices$ReactTemplate.make(question[0], question[1], index, /* array */[]));
                                      break;
                                  case 3 : 
                                      tmp = ReasonReact.element(undefined, undefined, MultipleChoices$ReactTemplate.make(question[0], question[1], index, /* array */[]));
                                      break;
                                  
                                }
                                return React.createElement("div", {
                                            key: String(index)
                                          }, tmp);
                              }), /* :: */[
                              /* TextField */Block.__(0, ["What's your name?"]),
                              /* :: */[
                                /* TextArea */Block.__(1, ["Please describe your experience with ReasonML."]),
                                /* :: */[
                                  /* AlternateChoices */Block.__(2, [
                                      "How long have you been studying FP?",
                                      /* :: */[
                                        "1-3 months",
                                        /* :: */[
                                          "3-12 months",
                                          /* :: */[
                                            "1+ years",
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]),
                                  /* :: */[
                                    /* MultipleChoices */Block.__(3, [
                                        "Please check the features you like the most in the language:",
                                        /* :: */[
                                          "Type safety",
                                          /* :: */[
                                            "Type inference",
                                            /* :: */[
                                              "Multi-platform compilation",
                                              /* :: */[
                                                "JS interop",
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var questionnaire = /* record */[
  /* description */"ReasonML Survey",
  /* questions : :: */[
    /* TextField */Block.__(0, ["What's your name?"]),
    /* :: */[
      /* TextArea */Block.__(1, ["Please describe your experience with ReasonML."]),
      /* :: */[
        /* AlternateChoices */Block.__(2, [
            "How long have you been studying FP?",
            /* :: */[
              "1-3 months",
              /* :: */[
                "3-12 months",
                /* :: */[
                  "1+ years",
                  /* [] */0
                ]
              ]
            ]
          ]),
        /* :: */[
          /* MultipleChoices */Block.__(3, [
              "Please check the features you like the most in the language:",
              /* :: */[
                "Type safety",
                /* :: */[
                  "Type inference",
                  /* :: */[
                    "Multi-platform compilation",
                    /* :: */[
                      "JS interop",
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]
  ]
];

exports.questionnaire = questionnaire;
exports.component = component;
exports.make = make;
/* component Not a pure module */
