// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function s(prim) {
  return prim;
}

function map(fn, l) {
  return $$Array.of_list(List.map(fn, l));
}

function mapi(fn, l) {
  return $$Array.of_list(List.mapi(fn, l));
}

exports.s = s;
exports.map = map;
exports.mapi = mapi;
/* No side effect */
