// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Answer$ReactTemplate = require("../src/Answer.bs.js");

describe("Answer", (function () {
        describe("contains", (function () {
                Jest.test("it does contain", (function (param) {
                        return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Answer$ReactTemplate.contains(Curry._1(Answer$ReactTemplate.make, "test"), "test")));
                      }));
                return Jest.test("it doesn't contain", (function (param) {
                              return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Answer$ReactTemplate.contains(Curry._1(Answer$ReactTemplate.make, "test"), "something else")));
                            }));
              }));
        describe("get", (function () {
                Jest.test("it retrieves an item", (function (param) {
                        return Jest.Expect[/* toBe */2]("test", Jest.Expect[/* expect */0](Answer$ReactTemplate.get(Curry._1(Answer$ReactTemplate.make, "test"))));
                      }));
                return Jest.test("it retrieves empty from an empty set", (function (param) {
                              return Jest.Expect[/* toBe */2]("", Jest.Expect[/* expect */0](Answer$ReactTemplate.get(Answer$ReactTemplate.empty)));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
